sudo: false
language: ruby
script: script/test
before_install:
  - gem install bundler -v 1.16.1
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
rvm:
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
