sudo: false
language: ruby
script: script/test
before_install:
  - bundle --version 2>/dev/null | grep -q '1.7.6' && gem install bundler -v 1.11.2 || true
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
